apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "wavefront-kubernetes-adapter.labels" . | indent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    app: custom-metrics-apiserver
