apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
  labels:
{{ include "wavefront-kubernetes-adapter.labels" . | indent 4 }}
    app: custom-metrics-apiserver
spec:
  service:
    name: custom-metrics-apiserver
    namespace: {{ .Release.Namespace }}
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
