apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "wavefront-kubernetes-adapter.labels" . | indent 4 }}
data:
  config.yaml: |
    rules: {{- toYaml .Values.rules | nindent 4 }}
