apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-metrics-server-resources
  labels:
{{ include "wavefront-kubernetes-adapter.labels" . | indent 4 }}
rules:
- apiGroups:
  - external.metrics.k8s.io
  resources: ["*"]
  verbs: ["get", "list"]
